# Generated by Django 5.1.4 on 2025-01-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stayease_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquiry',
            new_name='Enquirie',
        ),
    ]
